version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bank_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
      POSTGRES_DB: ${DATABASE_NAME:-bank_rest_db}
    ports:
      - "${DATABASE_PORT:-5435}:5432"
    volumes:
      - bank_pgdata:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d

  app:
    container_name: bank_rest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE_NAME:-bank_rest_db}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER:-admin}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD:-admin}
      SERVER_PORT: 8080
    depends_on:
      - db
    restart: always
    ports:
      - "${SERVER_PORT:-8080}:8080"

volumes:
  bank_pgdata:
