spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/migration/db.changelog-master.yml}

server:
  port: 8080